jobs:
  build:
    docker:
      - image: 'circleci/ruby:2.4.1'
    steps:
      - colony/start-sandbox:
          artifacts: "{}"
          blueprint: 'wordpress_aws_sample_Tokyo'
          inputs: "{'DB_USER': 'root', 'DB_PASS': '1234', 'DB_NAME': 'wordpress_demo', 'AWS_Type': 't2.micro'}"
          sandbox-name: 'test-sandbox'
      - run:
          command: 'echo "Sandbox ID is ${SANDBOX_ID}"'
          name: Fetch Details
      - colony/end-sandbox:
          sandbox-id: SANDBOX_ID
orbs:
  colony: quali/cloudshell-colony@1
version: 2.1
workflows:
  easy:
    jobs:
      - build
