jobs:
  build-and-publish:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run:
          command: |
            mkdir -p build_artifact
            tar -zcvf  ./build_artifact/wordpress-latest.tar.gz ./wordpress/*
          name: Archive app
      - aws-s3/copy:
          from: ./build_artifact/wordpress-latest.tar.gz
          to: "s3://colony-repository/"
orbs:
  aws-s3: circleci/aws-s3@1.0.11
  colony: quali/cloudshell-colony@1.0.4
version: 2.1
workflows:
  leadeasy:
    jobs:
      - build-and-publish
      - colony/sandbox:
          artifacts: "{'wordpress':'wordpress-latest.tar.gz'}"
          blueprint: wordpress_aws_sample_Tokyo_for_Artifact
          inputs: "{'DB_USER': 'root', 'DB_PASS': '1234', 'DB_NAME': 'wordpress_demo', 'AWS_Type': 't2.micro'}"
          name: Deploy Application
          requires:
            - build-and-publish
          sandbox-name: "wordpress-demo"
          steps:
            - run: echo "Do some testing here"
            - run: sleep 180
            - run:
                command: >
                  echo "Getting application endpoint"

                  SB_ENDPOINT="SB_${SANDBOX_ID}_SHORTCUT_1"

                  echo "Checking ${!SB_ENDPOINT}"

                  curl --write-out "%{http_code}\n" --silent --output /dev/null
                  "${!SB_ENDPOINT}"